# INFO: We are using localhost but its tunnel to aws

port: 28015
host: localhost
suffix: ec2_52_10_144_20
database: ha_ls_session_development
tables: ['api_key', 'ha_ls_sessions', 'request_api_log', 'response_api_log', 'offers']
